config/routes.rb
WinsPool::Application.routes.draw do
  resources :drafts

  resources :schedules

  resources :teams

  resources :users

  if @auth_user
    root :to => 'users#standings'
  else
    root :to => 'session#new'
  end

  match "/login" => "session#new", :via => :get
  match "/login" => "session#login", :via => :post
  match "/signup" => "users#new", :via => :get
  match "/logout" => "session#destroy", :via => "get"

  match "/test" => "teams#test", :via => "get"
  match "/testJS" => "teams#testJS", :via => :get

  match '/schedule/updateScore' => 'schedules#score', :via => :get

  match '/usermodal' => 'users#modal', :via => :get

  match '/standings' => 'users#standings', :via => :get

  match '/NFLStandings' => 'schedules#NFLStandings', :via => :get
  match '/NFLTeamSched' => 'schedules#NFLTeamSched', :via => :get

  match '/setNewWeek' => 'users#setNewWeek', :via => :post

  

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :teams, :through => :drafts 

has_many :drafts

has_one :wins_record

has_secure_password

def self.by_rank
	self.all.sort_by{|x| [x.wins_record.ranking]} 
end

scope :teamWins, joins(:teams).order('teams.wins DESC')

scope :order_by_wins, joins(:teams).select('users.id, sum(teams.wins) as total_wins').group('users.id').order('toal_wins desc')

scope :order_by_winz, joins(:teams).select('users.id, sum(teams.wins) as total_wins').order('total_wins DESC')  

scope :order_wins, select('id, wins as total_wins').order('total_wins DESC')

	def self.teamz
		self.drafts.each do |d|
			return d.player_id
		end
	end

	def ws
		return self.teams.sum(:wins)
	end

	def ls
		return self.teams.sum(:losses)
	end

	def ties
		return self.teams.sum(:ties)
	end

	def win_percent
		@games = self.wins.to_f + self.losses.to_f + self.ties.to_f
		return (self.wins.to_f/@games)
	end


	    # has_many :books, :through => :recommendations do
     #  def saved
     #    where("recommendations.self_saved = ?", true)
     #  end

     #  def sent
     #    where("recommendations.self_saved = ?", false) + where("recommendations.received = ?", false)
     #  end

     #  def received
     #    where("recommendations.received = ?", true)
     #  end

     #  def incoming
     #    where("recommendations.self_saved = ?", true) + where("recommendations.received = ?", true)
     #  end

     #  def active
     #    where("recommendations.active = ?", true)
     #  end

     #  def inactive
     #    where("recommendations.active = ?", false)
     #  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  include UsersHelper

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new

        respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    # {"utf8"=>"✓", "authenticity_token"=>"AS4EjE53ZO13TKDZSXwJvMCn4vgecYamoeFeT0NChRE=", "user"=>{"owner"=>"Bobby", "email"=>"bfegan@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Create User"}
    @user = User.new(user_params)
    # @user = User.new(:owner => params[:owner], :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation])
    # puts @user
    # @user.save

    respond_to do |format|
      if @user.save
        @auth_user = @user
        format.html { redirect_to @user, notice: 'Your spot in the league has been reserved!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new', notice: 'Glargenbargens!' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def modal
    @user = User.find(params[:userID])
    puts @user.owner

    respond_to do |format|
      format.js
    end
  end

  def standings
      @users = User.by_rank
      @updatedAt = Schedule.maximum('updated_at')
    respond_to do |format|
      format.html
      format.js
    end
  end


  def setNewWeek

    puts "~~~~hey!~~~~~~"
    @rankings = User.all.sort_by{|x| [x.wins, -x.losses]}.reverse
    setUsersForNewWeek(@rankings)
    # render nothing: true
    render file: 'users/setNewWeek.js.coffee'

  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:owner, :draft_order, :password, :password_confirmation, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def UpdateAllUserWLT
		User.all.each do |u|
			u.wins = u.ws
			u.losses = u.ls
			u.ties = u.ties
			u.save
		end
	end

	def UpdateUserWLT(usr)
			usr.wins = usr.ws
			usr.losses = usr.ls
			usr.ties = usr.ties
			usr.save
	end

	def getUserWinPercent(w, l, t)
		if w > 0 || l > 0 || t > 0
			@games = w + l + t
			@WinP = (w.to_f/@games.to_f)*1000
			if @WinP == 1000
				@wP = "1.000"
			elsif @WinP > 0 
				# @wP = "." + number_to_percentage(@WinP, precision: 0)
				# @WinP = @WinP.to_i
				@wP = ".#{@WinP.to_i}"
			else
				@wP = ".000"
			end
		else 
			@wP = ".000"
		end

			return @wP

	end

	def updateUserRankings(users)
		rankings = users.sort_by{|x| [x.wins, -x.losses]}.reverse
		i = 0
		while i < rankings.count
			u = rankings[i]
			u.wins_record.ranking = (i + 1)
			u.wins_record.games_back = (rankings[0].wins - u.wins)
			u.wins_record.save
			i += 1
		end
	end

	def setUsersForNewWeek(users)
		# rankings = User.by_rank
		i = 0
		while i < users.count
			u = users[i]
			# User.all.each do |u|
			winP = u.wins.to_f/(u.wins.to_f + u.losses.to_f + u.ties.to_f)
			r = u.wins_record
			r.last_wk_losses = r.current_wk_losses 
			r.last_wk_wins = r.current_wk_wins
			r.last_wk_ranking = r.current_wk_ranking
			r.last_wk_games_back = r.current_wk_games_back
			r.current_wk_losses = u.losses
			r.current_wk_wins = u.wins
			r.current_wk_games_back = r.games_back
			r.current_wk_ranking = r.ranking
			r.win_percentage = winP
			r.games_back = (users[0].wins - u.wins)
			r.ranking = i + 1
			r.save
			i += 1
		end

		end

	def getRankingChange(user)
		change = user.wins_record.last_wk_ranking - user.wins_record.ranking
			if change > 0
				@position = "<small class='xxsmall-text vertical-align-super text-success'>+#{change}</small>"
			elsif change == 0
					# @position = "<small class='xxsmall-text vertical-align-super'>--</small>"
					@position = ""
			elsif change < 0
				@position = "<small class='xxsmall-text vertical-align-super text-danger'>#{change}</small>"
			else
				@position = ""
			end
		return @position.html_safe
	end

	def getWinsChange(user)
		change = user.wins - user.wins_record.last_wk_wins
			if change > 0
				@position = "<small class='xxsmall-text vertical-align-super text-success'>+#{change}</small>"
			elsif change == 0
					# @position = "<small class='xxsmall-text vertical-align-super'>--</small>"
					@position = ""
			elsif change < 0
				@position = "<small class='xxsmall-text vertical-align-super text-danger'>#{change}</small>"
			else
				@position = ""
			end
		return @position.html_safe
	end

	def getLossesChange(user)
		change = user.losses - user.wins_record.last_wk_losses 
			if change > 0
				@position = "<small class='xxsmall-text vertical-align-super text-danger'>+#{change}</small>"
			elsif change == 0
					# @position = "<small class='xxsmall-text vertical-align-super'>--</small>"
					@position = ""
			elsif change < 0
				@position = "<small class='xxsmall-text vertical-align-super text-danger'>#{change}</small>"
			else
				@position = ""
			end
		return @position.html_safe
	end

	def getGamesBackChange(user)
		change = user.wins_record.last_wk_games_back - user.wins_record.games_back
			if change > 0
				@position = "<small class='xxsmall-text vertical-align-super text-success'>+#{change}</small>"
			elsif change == 0
					@position = "<small class='xxsmall-text vertical-align-super'>--</small>"
			elsif change < 0
				@position = "<small class='xxsmall-text vertical-align-super text-danger'>#{change}</small>"
			else
				@position = ""
			end
		return @position.html_safe
	end
		


end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  /
  .field
    = f.label :owner
    %br
      = f.text_field :owner
  .field
    = f.label :email
    %br
      = f.email_field :email
  .field
    = f.label :password
    = f.password_field :password, :autocomplete => 'off'
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation, :autocomplete => 'off'
  .actions
    = f.submit

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Draft order</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.owner %></td>
        <td><%= user.draft_order %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.haml
#SessionBox.col-md-offset-2
	%ul.nav.nav-tabs.col-md-10.sessionUL
		%li.sessionnav.col-md-6
			%a{:href => "/#"} 
				%h2.text-center Sign in
		%li.sessionnav.active.col-md-6
			%a{:href => "/#"} 
				%h2.text-center Sign up	

-# = render 'form'
#AccountDiv.col-md-offset-2.col-md-9.col-xs-12.col-xm-12.form-horizontal
	= render "shared/newUserTwo"

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @user.owner %>
</p>

<p>
  <strong>Draft order:</strong>
  <%= @user.draft_order %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
.jumbotron.headerJumbo
	.row
		.col-md-6.col-xs-6.col-sm-6
			-# %h2{:class => "col-md-5 textRight"} Round
			%h1{:class => "text-left"} #{@user.owner}
		.col-md-6.col-xs-6.col-sm-6
			%h2{:class => "col-md-5 textRight"} Wins
			%h1{:class => "text-center"} #{@user.wins}

	#UserRecord{:class => 'panel panel-success col-md-11 col-sm-11 col-xs-11 row'}
		%div{:class => 'panel-heading col-md-2 col-sm-12 col-xs-12 recordHeader'}
			%h3{:class => 'text-center'} Record
		
		%div{:class => ' col-md-10 col-xs-12 col-sm-12', :id => 'userRecordTable'}
			%table{:class => 'table table-striped table-hover'}
				%thead
					%th
						%h5{:class => 'text-center'} Win
					%th
						%h5{:class => 'text-center'} Loss
					%th
						%h5{:class => 'text-center'} Tie
					%th
						%h5{:class => 'text-center'} Win %
				%tr
					%th
						%h4{:class => 'text-center'} #{@user.wins}
					%th
						%h4{:class => 'text-center'} #{@user.losses}
					%th
						%h4{:class => 'text-center'} #{@user.ties}
					- getUserWinPercent(@user.wins, @user.losses, @user.ties)
					%th
						%h4{:class => 'text-center'} #{@wP}
						
= render partial: 'shared/userTeam', :locals => {:u => @user}

-# #UserTeams.col-md-10.col-md-offset-1.col-sm-12.col-xs-12
-# 	%table{:class => 'table table-striped table-hover'}
-# 		%tr
-# 			%th.col-md-5.col-md-offset-1.col-sm-5.col-xs-5.text-left Team
-# 			%th.col-md-1.col-sm-1.col-xs-1.text-center Win
-# 			%th.col-md-1.col-sm-1.col-xs-1.text-center   Loss
-# 			%th.col-md-1.col-sm-1.col-xs-1.text-center   Tie
-# 			%th.col-md-2.col-sm-2.col-xs-2.text-center  Win %
-# 		- @user.teams.each do |t|
-# 			%tr
-# 				%td.text-left #{t.city} #{t.name}
-# 				%td.text-center #{t.wins}
-# 				%td.text-center #{t.losses}
-# 				%td.text-center #{t.ties}
-# 				- if t.wins > 0 || t.losses > 0 || t.ties > 0
-# 					- @gms = t.wins + t.losses + t.ties
-# 					- @winp = t.wins.to_f/@gms.to_f
-# 					%td.text-center #{@winp.to_f}
-# 				- else
-# 					%td.text-center .000%

app/views/users/showOLD.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @user.owner %>
</p>

<p>
  <strong>Draft order:</strong>
  <%= @user.draft_order %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/standings.html.haml
.jumbotron.headerJumbo.row
	%h1.pull-left.clearNone Pool Standings
	%p.small.i.pull-right.clearNone.updatedAt Scores Updated at: #{@updatedAt.in_time_zone("Eastern Time (US & Canada)").strftime('%l:%M %p %a, %b %-d')}

#StandingsBody.contentTable
	%p
		%small
			%em Click a player to see their teams
	#UserTeams.col-md-12.col-sm-12.col-xs-12
		%table{:class => 'table table-striped table-hover standingsTable'}
			%tr
				%th.col-md-1.col-sm-1.col-xs-1.text-left
					%h5.text-left 
						Rank
						%small.xxsmall-text.vertical-align-super
							Change
				%th.col-md-4.col-md-offset-1.col-sm-2.col-xs-2.text-left
					%h5.text-left Player
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h5.text-center Win
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h5.text-center   Loss
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h5.text-center   Tie
				%th.col-md-2.col-sm-2.col-xs-2.text-center
					%h5.text-center  Win %
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h5.text-center   GB
			- i = 1
			- @users.each do |u|
				- if u.id == @auth_user.id
					- @highlight = "trow-warning-bs"
				- else
					- @highlight = ""
				%tr.playerTeam{:"data-userid" => "#{u.id}", :class => @highlight }
					%td.text-center
						%h4.text-left
							#{i}
							= getRankingChange(u)
					%td.text-left
						%h4.text-left #{u.owner}
					%td.text-center
						%h4.text-center
							#{u.wins}
							= getWinsChange(u)
					%td.text-center
						%h4.text-center
							#{u.losses}
							= getLossesChange(u)
					%td.text-center
						%h4.text-center #{u.ties}
					- getUserWinPercent(u.wins, u.losses, u.ties)
					%td.text-center
						%h4.text-center #{@wP}
					- if u == @users[0]
						%td.text-center
							%h4 --- #{getGamesBackChange(u)}
					- else
						
						%td.text-center
							%h4 
								#{u.wins_record.games_back}
								= getGamesBackChange(u)
				- i += 1
					