config/routes.rb
WinsPool::Application.routes.draw do
  resources :drafts

  resources :schedules

  resources :teams

  resources :users

  if @auth_user
    root :to => 'users#standings'
  else
    root :to => 'session#new'
  end

  match "/login" => "session#new", :via => :get
  match "/login" => "session#login", :via => :post
  match "/signup" => "users#new", :via => :get
  match "/logout" => "session#destroy", :via => "get"

  match "/test" => "teams#test", :via => "get"
  match "/testJS" => "teams#testJS", :via => :get

  match '/schedule/updateScore' => 'schedules#score', :via => :get

  match '/usermodal' => 'users#modal', :via => :get

  match '/standings' => 'users#standings', :via => :get

  match '/NFLStandings' => 'schedules#NFLStandings', :via => :get
  match '/NFLTeamSched' => 'schedules#NFLTeamSched', :via => :get

  match '/setNewWeek' => 'users#setNewWeek', :via => :post

  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  include UsersHelper
  include SchedulesHelper
  # before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    if params[:weekNumber]
      if params[:weekNumber] == "All"
        @schedules = Schedule.all.order("date ASC")
      else
        @wkNum = params[:weekNumber]
        @schedules = Schedule.where(:week => @wkNum).order("date ASC")
      end
    else
      determineWeekNum(Time.now)
      if @thisWk == "Nope"
        @schedules = Schedule.all.order("date ASC")
      else
        @schedules = Schedule.where(:week => @thisWk).order("date ASC")
      end
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    # respond_to do |format|
    #   if @schedule.save
    #     format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @schedule }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @schedule.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    # respond_to do |format|
    #   if @schedule.update(schedule_params)
    #     format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @schedule.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  def NFLTeamSched
    if params[:teamID]
      @teamID = params[:teamID]
      @gms = Schedule.where(:home_id => @teamID) + Schedule.where(:visitor_id => @teamID)
      @games = @gms.sort_by{|g| g[:date]}
      @games.each do |g|
        puts g.date
      end
      @team = Team.find(@teamID)
    end

    respond_to do |format|
      format.js
    end


  end

  def NFLStandings

    @teams = Team.all.order('wins DESC')
    @updatedAt = Schedule.maximum('updated_at')

    respond_to do |format|
      format.html
      format.json
    end

  end


  def score
    @game = Schedule.find(params[:gameID])
    @game.visitor_score = params[:vTeamScore]
    @game.home_score = params[:hTeamScore]
    @vScore = params[:vTeamScore].to_i
    @hScore = params[:hTeamScore].to_i
    @hTeam = Team.find(params[:hTeamID])
    @vTeam = Team.find(params[:vTeamID])

    if params[:winner] == "tbd"
      if @vScore > @hScore
        @game.winning_team_id = params[:vTeamID]
        SetTeamRecords(params[:vTeamID], params[:hTeamID])
      elsif @hScore > @vScore
        @game.winning_team_id = params[:hTeamID]
        SetTeamRecords(params[:hTeamID], params[:vTeamID])
      elsif @hScore == @vScore
        @game.winning_team_id = nil
        @tie = true
        SetTeamTies(params[:hTeamID], params[:vTeamID])
      end

      @game.save


      puts "================Saving new game================"

    elsif params[:winner] == "home"
      if @vScore > @hScore
        @game.winning_team_id = params[:vTeamID]
        AdjustTeamRecords(params[:hTeamID], params[:vTeamID])
        SetTeamRecords(params[:vTeamID], params[:hTeamID])
      elsif @hScore > @vScore
        @game.save
      elsif @hScore == @vScore
        @game.winning_team_id = nil
        @tie = true
        SetTeamTies(params[:hTeamID], params[:vTeamID])
      end

      @game.save

      puts "========Editing Old Game (Old winner was home) ================"
    
    elsif params[:winner] == "visitor"
      if @hScore > @vScore
        @game.winning_team_id = params[:hTeamID]
        AdjustTeamRecords(params[:vTeamID], params[:hTeamID])
        SetTeamRecords(params[:hTeamID], params[:vTeamID])
      elsif @vScore > @hScore
        @game.save
      elsif @hScore == @vScore
        @game.winning_team_id = nil
        @tie = true
        SetTeamTies(params[:vTeamID], params[:hTeamID])
      end
  
      @game.save

       puts "========Editing Old Game (Old winner was VISITOR) ================"

    end


    if @hTeam.taken == true
      @hUser = @hTeam.user
      UpdateUserWLT(@hUser)
      UpdateWLT(@hUser)
    end

    if @vTeam.taken == true
      @vUser = @vTeam.user
      UpdateUserWLT(@vUser)
      UpdateWLT(@vUser)
    end

    updateUserRankings(User.all)
    

    @schedules = Schedule.all
    @schedule = @game

    respond_to do |format|
      format.js
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_schedule
    #   @schedule = Schedule.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def schedule_params
    #   params.require(:schedule).permit(:week, :date, :visitor_id, :home_id, :visitor_score, :home_score, :winning_team_id)
    # end
end

app/helpers/schedules_helper.rb
module SchedulesHelper


		def UpdateWLT(usr)
			usr.wins = usr.ws
			usr.losses = usr.ls
			usr.ties = usr.ties
			usr.save
	end


	def getGameStatus(date)
		if Time.now() > date && (Time.now - date) < 100000
			@color = "text-warning"
		elsif Time.now() > date
			@color = "text-danger"
		else
			@color = ""
		end

		return @color
		end

	def AddLoss(team)
		@team = Team.find(team)
		@team.losses += 1
		@team.save
	end


	def AddWin(team)
		@team = Team.find(team)
		@team.wins += 1
		@team.save
	end

	def RemoveWin(team)
		@team = Team.find(team)
		@team.wins -= 1
		@team.save
	end

	def RemoveLoss(team)
		@team = Team.find(team)
		@team.losses -= 1
		@team.save
	end

	def SetTeamRecords(winner, loser)
		@wTeam = Team.find(winner)
		@wTeam.wins += 1
		@wTeam.save
		@lTeam = Team.find(loser)
		@lTeam.losses += 1
		@lTeam.save
		puts "Set Team Records Helper!"
	end

	def AdjustTeamRecords(winner, loser)
		@wTeam = Team.find(winner)
		@wTeam.wins -= 1
		@wTeam.save
		@lTeam = Team.find(loser)
		@lTeam.losses -= 1
		@lTeam.save
		puts "Adjust Team Records Helper!"
	end

	def SetTeamTies(home, visitor)
		@hTeam = Team.find(winner)
		@hTeam.ties += 1
		@hTeam.save
		@hTeam = Team.find(loser)
		@hTeam.ties += 1
		@hTeam.save
		puts "Set Team Ties Helper!"
	end

	def determineWeekNum(time)
		Week.all.each do |w|
			if w.start_date.past? && w.end_date.future?
				@thisWk = w.weekNum
			end
		end

		if @thisWk.nil?
			@thisWk = "Nope"
		end

		return @thisWk
	end

end

app/views/schedules/NFLStandings.html.haml
.jumbotron.headerJumbo.row
	%h1.pull-left.clearNone NFL Standings
	%p.small.i.pull-right.clearNone.updatedAt Scores Updated at: #{@updatedAt.in_time_zone("Eastern Time (US & Canada)").strftime('%l:%M %p %a, %b %-d')}

#StandingsBody.contentTable
	%p
		%small
			%em Click a team to see its schedule & results
			%br
			%span.trow-info-bs Highlighted teams are undrafted
	#UserTeams.col-md-12.col-sm-12.col-xs-12
		%table{:class => 'table table-striped table-hover standingsTable table-condensed'}
			%tr
				%th.col-md-1.col-sm-1.col-xs-1.text-left
					%h6.text-left Rnk.
				%th.col-md-4.col-md-offset-1.col-sm-3.col-xs-3.text-left
					%h6.text-left Team
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h6.text-center Win
				%th.col-md-1.col-sm-1.col-xs-2.text-center
					%h6.text-center   Loss
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h6.text-center   Tie
				%th.col-md-2.col-sm-2.col-xs-2.text-center
					%h6.text-center  Win %
				%th.col-md-1.col-sm-1.col-xs-1.text-center
					%h6.text-center   GB
			- i = 1
			- @teams.each do |u|
				- if u.taken == false
					- @highlight = "trow-info-bs"
				- else
					- @highlight = "bleh"
				%tr.NFLTeamSched{:"data-teamid" => "#{u.id}", :class => @highlight}
					%td.text-left
						%h5.text-left.text-centerAlign #{i}
					%td.text-left
						%h5.text-left #{u.city} #{u.name}
					%td.text-center
						%h5.text-center #{u.wins}
					%td.text-center
						%h5.text-center #{u.losses}
					%td.text-center
						%h5.text-center #{u.ties}
					- getUserWinPercent(u.wins, u.losses, u.ties)
					%td.text-center
						%h5.text-center #{@wP}
					- if u.wins == @teams[0].wins
						%td.text-center
							%h5 --
					- else
						- @gb = @teams[0].wins - u.wins
						%td.text-center
							%h5 #{@gb}
					- i += 1

-# #NFLTeamModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "PlayerModalLabel", :role => "dialog", :tabindex => "-1"}

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :visitor_id %><br>
    <%= f.number_field :visitor_id %>
  </div>
  <div class="field">
    <%= f.label :home_id %><br>
    <%= f.number_field :home_id %>
  </div>
  <div class="field">
    <%= f.label :visitor_score %><br>
    <%= f.number_field :visitor_score %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br>
    <%= f.number_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :winning_team_id %><br>
    <%= f.number_field :winning_team_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Date</th>
      <th>Visitor</th>
      <th>Home</th>
      <th>Visitor score</th>
      <th>Home score</th>
      <th>Winning team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.week %></td>
        <td><%= schedule.date %></td>
        <td><%= schedule.visitor_id %></td>
        <td><%= schedule.home_id %></td>
        <td><%= schedule.visitor_score %></td>
        <td><%= schedule.home_score %></td>
        <td><%= schedule.winning_team_id %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/index.html.haml
.row#SchedHead.jumbotron.headerJumbo.row	
	%h1.col-md-4.margin-bottom-0  Games
	- determineWeekNum(Time.now)
	%div.btn-toolbar.pull-right
		%h5.col-md-1.col-xs-1.col-sm-1.text-center Week:
		%div{:class => 'btn-group'}
			- @y = Schedule.minimum('week')
			- while @y <= Schedule.maximum('week')
				-if @y == @thisWk
					%button{:class => 'btn btn-sm btn-default wkBtn active', :'data-wk' => @y, :id => "Week#{@y}"} #{@y}
				- else
					%button{:class => 'btn btn-sm btn-default wkBtn', :'data-wk' => @y, :id => "Week#{@y}"} #{@y}
				- @y += 1
		%div{:class => 'btn-group'}
			%button{:class => 'btn btn-sm  btn-info wkBtn', :'data-wk' => 'All', :id => 'All'} Show All
			%div{:class => 'btn-toolbar'}
	- if @auth_user.admin? 
		.row.col-md-12.col-sm-12.col-xs-12.col-lg-12.clearBoth.margin-top-0.margin-right-0
			.div.pull-right.margin-top-0
				= link_to setNewWeek_path, method: :post, remote: true do
					%button.btn.btn-sm.btn-success#SetNewWeek Set New Week
				-# %button.btn.btn-sm Set New Week

%div.col-md-11.col-xs-12.schedTable.contentTable
	%table.table.table-striped.table-hover.col-md-12.col-xs-12.col-sm-12.margin-left-0.padding-left-0
		%thead
			%tr
				-# %th.col-md-1.col-xs-1
				-# 	%h5.text-center Week
				%th.col-md-1.col-xs-1
					%h5.text-center  Date
				%th.col-md-1.col-xs-1
					%h5.text-center  Time
				%th.col-md-3.col-xs-3
					%h5.text-left  Visitor
				%th.col-md-1.col-xs-1
					%h5.text-center  Score
				%th.col-md-3.col-xs-3
					%h5.text-left  Home
				%th.col-md-1.col-xs-1
					%h5.text-center  Score
				%th.col-md-1.col-xs-1
					%h5.text-center Status
		%tbody#gamesTable
			= render :partial => 'shared/gamesRow', :locals => {:schedules => @schedules}
			

app/views/schedules/indexOLD.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Date</th>
      <th>Visitor</th>
      <th>Home</th>
      <th>Visitor score</th>
      <th>Home score</th>
      <th>Winning team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.week %></td>
        <td><%= schedule.date %></td>
        <td><%= schedule.visitor_id %></td>
        <td><%= schedule.home_id %></td>
        <td><%= schedule.visitor_score %></td>
        <td><%= schedule.home_score %></td>
        <td><%= schedule.winning_team_id %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week:</strong>
  <%= @schedule.week %>
</p>

<p>
  <strong>Date:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>Visitor:</strong>
  <%= @schedule.visitor_id %>
</p>

<p>
  <strong>Home:</strong>
  <%= @schedule.home_id %>
</p>

<p>
  <strong>Visitor score:</strong>
  <%= @schedule.visitor_score %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @schedule.home_score %>
</p>

<p>
  <strong>Winning team:</strong>
  <%= @schedule.winning_team_id %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>