config/routes.rb
WinsPool::Application.routes.draw do
  resources :drafts

  resources :schedules

  resources :teams

  resources :users

  if @auth_user
    root :to => 'users#standings'
  else
    root :to => 'session#new'
  end

  match "/login" => "session#new", :via => :get
  match "/login" => "session#login", :via => :post
  match "/signup" => "users#new", :via => :get
  match "/logout" => "session#destroy", :via => "get"

  match "/test" => "teams#test", :via => "get"
  match "/testJS" => "teams#testJS", :via => :get

  match '/schedule/updateScore' => 'schedules#score', :via => :get

  match '/usermodal' => 'users#modal', :via => :get

  match '/standings' => 'users#standings', :via => :get

  match '/NFLStandings' => 'schedules#NFLStandings', :via => :get
  match '/NFLTeamSched' => 'schedules#NFLTeamSched', :via => :get

  match '/setNewWeek' => 'users#setNewWeek', :via => :post

  

end

app/views/shared/_draftHeader.html.haml
.row{:class => "col-md-4 col-sm-4 col-xs-12"}
	%h2{:class => "col-md-5 col-sm-5 col-xs-5 text-left"} Round:
	%h1{:class => "col-md-7 col-sm-7 col-xs-7 text-center", :id => "roundNum"} #{@roundNum}
.row{:class => "col-md-4 col-sm-4 col-xs-12"}
	%h2{:class => "col-md-5 col-sm-5 col-xs-5 text-left"} Pick:
	%h1{:class => "col-md-7 col-sm-7 col-xs-7 text-center", :id => "pickNum"} #{@pickNum}
.row{:class => "col-md-4 col-sm-4 col-xs-12"}
	%h2{:class => "col-md-3 col-sm-3 col-xs-3 text-left"} Picking:
	%h1{:class => "col-md-9 col-sm-9 col-xs-9 text-right", :id => "teamPicking", :'data-tID' => @userName.id } #{@userName.owner}
-# %h1{:class => "col-md-4 textRight", :id => "teamPicking", :'data-tID' => @userName.name } #{@userName.owner}

app/views/shared/_draftSuccessModal.html.haml
.modal-dialog
	.modal-content
		.modal-header
			%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
			%h4.modal-title Success!
		.modal-body
			You've successfully drafted the #{t.city} #{t.name}!
			%br
			%br
			-# Click here to send an email to #{u.owner}, who's now on the clock.

			%a{:href => "mailto:#{u.email}?cc=bfegan@gmail.com&subject=Your turn to draft&body=Hi #{u.owner}, it's your turn to draft! \r\n Follow this link to make your pick: http://winspool.heroku.com/drafts", :class => 'nextDraftLink' } Click here to send an email to #{u.owner}, who's now on the clock.

			-# <a href="mailto:test@test.test?body=The message's first paragraph.%0A%0aSecond paragraph.%0A%0AThird Paragraph.%0A%0ALink goes here">Link text goes here</a>

			-# ->setBody("Did you request a password reset for your account?\r\n\r\nIf yes, click here:\r\nhttp://www.website.com", 'text/plain');
			-# %table{:class => 'table table-striped table-condensed'}
			-# 	- @y = 1
			-# 	%tr
			-# 		%th{:class => 'col-md-1'} Position
			-# 		%th{:class => 'col-md-1'} Slots
			-# 		%th{:class => 'col-md-1'} Drafted
			-# 		%th{:class => 'col-md-5'} Players
			-# 		%th{:class => 'col-md-1'} Proj. Points
			-# 		%th{:class => 'col-md-1'} Proj. Weekly
			-# 	= render :partial => "shared/teamPosRow", :locals => {:p => @myQBs, :name => "QB", :pa => @posAvail, :y => @y }
			-# 	- @y += 1
			-# 	= render :partial => "shared/teamPosRow", :locals => {:p => @myRBs, :name => "RB", :pa => @posAvail, :y => @y }
			-# 	- @y += 1
			-# 	= render :partial => "shared/teamPosRow", :locals => {:p => @myWRs, :name => "WR", :pa => @posAvail, :y => @y }
			-# 	- @y += 1
			-# 	= render :partial => "shared/teamPosRow", :locals => {:p => @myTEs, :name => "TE", :pa => @posAvail, :y => @y }
			-# 	- @y += 1
			-# 	= render :partial => "shared/teamPosRow", :locals => {:p => @myPKs, :name => "PK", :pa => @posAvail, :y => @y }
			-# 	- @y += 1
			-# 	= render :partial => "shared/teamPosRow", :locals => {:p => @myDefs, :name => "Def", :pa => @posAvail, :y => @y }
			-# 	- @y += 1
			-# 	%tr
			-# 		%th{:class => 'col-md-1'} Total
			-# 		%th #{@posAvail["Total"]}
			-# 		%th #{@myPlayers.count}
			-# 		%th 
			-# 		%th
			-# 			= SumPosPoints(@myPlayers, "rank3")
			-# 		%th
			-# 			= CalcWeeklyPoints(@posPoints, 12)

app/views/shared/_draftSummary.html.haml
-# %p @roundNum: #{@roundNum}, pickNum: #{@pickNum}, @blankCol: #{@blackCol}, @drafters: #{@drafters}
-# %table{:class => 'table table-striped table-condensed draftSummaryTable', :id => 'vertTable'}
-# 	%tr
-# 		%th{:class => 'rndCol centerText'} Rnd.
-# 		- @numUsrs = @usersList.count
-# 		- @usersList.each do |t|
-# 			%th{:class => 'centerText'}
-# 				=link_to t.owner, user_path(t.id)
-# 	- i = 1
-# 	- while i < @roundNum + 1
-# 		%tr
-# 			%td{:class => 'rndNumRow vAlignMiddle centerText'} #{i}
-# 			- if i.even?
-# 				- if i == @roundNum
-# 					- @blankCol = (@drafters - @pickNum) + 2
-# 					- x = 1
-# 					- while x < @blankCol
-# 						%td
-# 						- x += 1
-# 				- @playersRev = Draft.where(:round => i).order("pick DESC")
-# 				- @playersRev.each do |d|
-# 					- p = Team.find(d.team_id)
-# 					%td{:class => 'centerText vAlignMiddle'}
-# 						%h6 #{p.name}
-# 			- else
-# 				- Draft.where(:round => i).each do |d|
-# 					- p = Team.find(d.team_id)
-# 					%td{:class => 'centerText vAlignMiddle'}
-# 						%h6 #{p.name}
-# 		- i += 1
-# #dwlXLSlink
-# 	= link_to "Download Spreadsheet", "/active.xls", :class => 'btn btn-sm btn-success dwlSummaryBtn'


%table{:class => 'table table-striped table-condensed draftSummaryTable', :id => 'horzTable'}
	%tr
		%th{:class => 'rndCol centerText col-xs-1'} Rnd.
		- @numUsrs = @usersList.count
		- @usersList.each do |t|
			%th{:class => 'centerText col-xs-1 dSumTeam', :'data-userID' => "#{t.id}"} #{t.owner}
			-# =link_to t.owner, user_path(t.id)
			
	%tr	
	- i = 1
	- while i < @roundNum + 1
		%tr
			%td{:class => 'rndNumRow vAlignMiddle centerText'} #{i}
			- x = 0
			- while x < @drafters
				- y = i - 1
				- @u = @usersList[x]
				- if @u.teams[y].nil?
					%td
				- else
					%td{:class => 'centerText vAlignMiddle'}
						%h6 #{@u.teams[y].name}
				- x += 1
		- i += 1

app/views/shared/_gameRow.html.haml
- @vTeam = Team.find(s.visitor_id)
- @hTeam = Team.find(s.home_id)
- if @vTeam.id == s.winning_team_id
	- @vTeamText = "text-success"
	- @hTeamText = "text-danger"
	- @winner = "visitor"
- elsif @hTeam.id == s.winning_team_id
	- @hTeamText = "text-success"
	- @vTeamText = "text-danger"
	- @winner = "home"
- elsif s.date.past?
	- @vTeamText = "text-warning"
	- @hTeamText = "text-warning"
	- @winner = "tbd"
- else
	- @vTeamText = ""
	- @hTeamText = ""
	- @winner = "tbd"
-# %td{:class => 'centerText'} #{s.week}
%td
	%h5.text-center #{s.date.strftime('%a, %b %-d')}
%td
	%h5.text-center #{s.date.strftime('%l:%M %p')}
%td.tableBorderLeft
	%h4{:class => "#{@vTeamText}"} #{@vTeam.city} #{@vTeam.name}
- if s.visitor_score.nil?
	%td.col-md-1.col-xs-1{:id => "Game#{s.id}VScore"}
		- if @auth_user.admin?
			%input.form-control{:id => "vTeam#{s.id}"}
- else
	%td.col-md-1.col-xs-1{:id => "Game#{s.id}VScore"}
		%h4.text-center #{s.visitor_score}
%td.tableBorderLeft
	%h4{:class => "#{@hTeamText}  text-left"} #{@hTeam.city} #{@hTeam.name}
- if s.home_score.nil?
	%td{:class => 'col-md-1 col-xs-1', :id => "Game#{s.id}HScore"}
		%input.form-control{:id => "hTeam#{s.id}"}  
- else
	%td{:id => "Game#{s.id}HScore"}  
		%h4.text-center #{s.home_score}
- if @auth_user.admin?
	- if s.winning_team_id.nil?
		%td.tableBorderLeft.text-center
			%button.btn.btn-info.btn-sm.saveGame.tableBorderLeft.text-center.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving...", :'data-winner' => "#{@winner}"} Save
	- else
		%td.tableBorderLeft.text-center
			%button.btn.btn-caution.btn-sm.editGame.tableBorderLeft.text-center.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving...", :'data-winner' => "#{@winner}"} Edit
- else
	- if s.date.past?
		- if s.winning_team_id.nil?
			%td.unAuthGame.tableBorderLeft.text-center
				%button.btn.btn-warning.btn-sm.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving..."} In Progress
		- else
			%td.unAuthGame.tableBorderLeft.text-center 
				%button.btn.btn-danger.btn-sm.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving..."} Final

app/views/shared/_gamesRow.html.haml
- schedules.each do |s|
	%tr.gameSchedRow{:id => "GameRow#{s.id}"}
		- @vTeam = Team.find(s.visitor_id)
		- @hTeam = Team.find(s.home_id)
		- if @vTeam.id == s.winning_team_id
			- @vTeamText = "text-success"
			- @hTeamText = "text-danger"
			- @winner = "visitor"
		- elsif @hTeam.id == s.winning_team_id
			- @hTeamText = "text-success"
			- @vTeamText = "text-danger"
			- @winner = "home"
		- elsif s.date < Time.now
			- @vTeamText = "text-warning"
			- @hTeamText = "text-warning"
			- @winner = "tbd"
		- else
			- @vTeamText = ""
			- @hTeamText = ""
			- @winner = "tbd"
		-# %td
		-# 	%h5.text-center{:class => 'centerText'} #{s.week}
		%td
			%h5.text-center #{s.date.strftime('%a, %b %-d')}
		%td
			%h5.text-center #{s.date.strftime('%l:%M %p')}
		%td.tableBorderLeft
			%h4{:class => "#{@vTeamText}"} #{@vTeam.city} #{@vTeam.name}
		- if s.visitor_score.nil?
			%td.col-md-1.col-xs-1{:id => "Game#{s.id}VScore"}
				- if @auth_user.admin?
					%input.form-control{:id => "vTeam#{s.id}"}
		- else
			%td.col-md-1.col-xs-1{:id => "Game#{s.id}VScore"}
				%h4.text-center #{s.visitor_score}
		%td.tableBorderLeft
			%h4{:class => "#{@hTeamText}  text-left"} #{@hTeam.city} #{@hTeam.name}
		- if s.home_score.nil?
			%td{:class => 'col-md-1 col-xs-1', :id => "Game#{s.id}HScore"}
				- if @auth_user.admin?
					%input.form-control{:id => "hTeam#{s.id}"} 
		- else
			%td{:id => "Game#{s.id}HScore"} 
				%h4.text-center #{s.home_score}
		- if @auth_user.admin?
			- if s.winning_team_id.nil?
				%td.tableBorderLeft.text-center
					%button.btn.btn-info.btn-sm.saveGame.tableBorderLeft.text-center.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving...", :'data-winner' => "#{@winner}"} Save
			- else
				%td.tableBorderLeft.text-center
					%button.btn.btn-caution.btn-sm.editGame.tableBorderLeft.text-center.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving...", :'data-winner' => "#{@winner}"} Edit
		- else
			- if s.date < Time.now
				- if s.winning_team_id.nil?
					%td.unAuthGame.tableBorderLeft.text-center
						%button.btn.btn-warning.btn-sm.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving..."} In Progress
				- else
					%td.unAuthGame.tableBorderLeft.text-center 
						%button.btn.btn-danger.btn-sm.schedGame{:'data-sid' => "#{s.id}", :'data-vteam' => "#{@vTeam.id}", :'data-hteam' => "#{@hTeam.id}", :"data-loading-text" => "Saving..."} Final

app/views/shared/_jbTeamModal.html.haml
.modal-dialog
	.modal-content
		.modal-header
			%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
			%h4.modal-title #{teamName}
		.modal-body
			%table{:class => 'table table-striped table-condensed'}
				- @y = 1
				%tr
					%th{:class => 'col-md-1'} Position
					%th{:class => 'col-md-1'} Slots
					%th{:class => 'col-md-1'} Drafted
					%th{:class => 'col-md-5'} Players
					%th{:class => 'col-md-1'} Proj. Points
					%th{:class => 'col-md-1'} Proj. Weekly
				= render :partial => "shared/teamPosRow", :locals => {:p => @jbQBs, :name => "QB", :pa => @posAvail, :y => @y }
				- @y += 1
				= render :partial => "shared/teamPosRow", :locals => {:p => @jbRBs, :name => "RB", :pa => @posAvail, :y => @y }
				- @y += 1
				= render :partial => "shared/teamPosRow", :locals => {:p => @jbWRs, :name => "WR", :pa => @posAvail, :y => @y }
				- @y += 1
				= render :partial => "shared/teamPosRow", :locals => {:p => @jbTEs, :name => "TE", :pa => @posAvail, :y => @y }
				- @y += 1
				= render :partial => "shared/teamPosRow", :locals => {:p => @jbPKs, :name => "PK", :pa => @posAvail, :y => @y }
				- @y += 1
				= render :partial => "shared/teamPosRow", :locals => {:p => @jbDefs, :name => "Def", :pa => @posAvail, :y => @y }
				- @y += 1
				%tr
					%th{:class => 'col-md-1'} Total
					%th #{@posAvail["Total"]}
					%th #{@jbPlayers.count}
					%th 
					%th
						= SumPosPoints(@jbPlayers, "rank3")
					%th
						= CalcWeeklyPoints(@posPoints, 12)

app/views/shared/_newUser.html.haml
#AccountDiv.col-md-offset-2.col-md-10.col-xs-12.col-xm-12.form-horizontal
	= form_for(@user) do |f|
		- if @user.errors.any?
		#error_explanation
			%h2
			= pluralize(@user.errors.count, "error")
			prohibited this user from being saved:
			%ul
			- @user.errors.full_messages.each do |msg|
				%li= msg
		.form-group
			%h4.col-md-2.control-label.text-center Name:
			.col-md-8
				= f.text_field :owner, nil, :class => 'form-control col-md-8'
		.form-group
			%h4.col-md-2.control-label.text-center Email:
			.col-md-8
				= f.text_field :email, nil, :class => 'form-control col-md-8'
		.form-group
			%h4.col-md-2.control-label.text-center{:for => "inputPassword1"} Password:
			.col-md-8
				= f.password_field :password, nil, :class => 'form-control', :autocomplete => 'off'
		.form-group
			%h4.col-md-2.control-label.text-center{:for => "inputPassword1"} Confirm Password:
			.col-md-8
				= f.password_field :password_confirmation, nil, :class => 'form-control', :autocomplete => 'off'
		= f.submit "Sign Up", :class => "btn btn-primary btn-large col-md-2 col-md-offset-8 col-xs-12 col-sm-12 usrSubmitBtn"

app/views/shared/_newUserTwo.html.haml
= form_for(@user) do |f|
	- if @user.errors.any?
		#error_explanation
			%h2
				= pluralize(@user.errors.count, "error")
				prohibited this user from being saved:
			%ul
				- @user.errors.full_messages.each do |msg|
					%li= msg
	/
	-# .field
	-# 	= f.label :owner
	-# 	%br
	-# 		= f.text_field :owner
	.form-group
		%h4.col-md-2.control-label.text-center Name:
		-# = f.label "Name: ", :class => "col-md-2 col-xs-3 control-label text-center"
		.col-md-8.col-xs-9
			= f.text_field :owner, :class => 'form-control col-md-8 col-xs-9'
	.form-group
		%h4.col-md-2.control-label.text-center Email:
		.col-md-8.col-xs-9
			= f.email_field :email, :class => 'form-control col-md-8 col-xs-9'
	.form-group
		%h4.col-md-2.control-label.text-center Password:
		.col-md-8.col-xs-9
			= f.password_field :password, :class => 'form-control col-md-8 col-xs-9'
	.form-group
		%h4.col-md-2.control-label.text-center Confirm Password:
		.col-md-8.col-xs-9
			= f.password_field :password_confirmation, :class => 'form-control col-md-8 col-xs-9'
	-# .field
	-# 	= f.label :email
	-# 	%br
	-# 		= f.email_field :email
	-# .field
	-# 	= f.label :password
	-# 	= f.password_field :password, :autocomplete => 'off'
	-# .field
	-# 	= f.label :password_confirmation
	-# 	= f.password_field :password_confirmation, :autocomplete => 'off'
	.actions
		= f.submit "Sign Up", :class => "btn btn-primary btn-large col-md-2 col-md-offset-8 col-xs-12 col-sm-12 usrSubmitBtn"

app/views/shared/_nflTeamSched.html.haml
.modal-dialog
	.modal-content
		.modal-header.schedModal
			%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
			%h4.modal-title.col-sm-11.col-xs-11 #{t.city} #{t.name} 2013 Schedule
			- if t.taken?
				%h6.modal-title.col-sm-11.col-xs-11 Owner: <span class="i"> #{t.user.owner}
			- else
				%h6.modal-title.col-sm-12.col-xs-12 Owner: <span class="i">  Undrafted
		.modal-body.teamModalBdy
			%table.table.table-striped.table-condensed.table-bordered
				%tr
					%th.col-md-1.col-sm-1.col-xs-1
						%h6.text-center Wk.
					%th.col-md-2.col-sm-2.col-xs-2
						%h6.text-center Date
					%th.col-md-2.col-sm-2.col-xs-2
						%h6.text-center Time
					%th.col-md-5.col-sm-5.col-xs-5
						%h6.text-center  Opponent
					%th.col-md-2.col-sm-2.col-xs-2
						%h6.text-center Result
				- games.each do |g|
					- getGameStatus(g.date)
					- if g.winning_team_id.nil?
						- @score = ""
						- @color = ""
					- else
						- if g.winning_team_id == t.id
							- @score = "W #{g.visitor_score} - #{g.home_score}"
							- @color = "text-success"
						- elsif g.winning_team_id != t.id
							- @score = "L #{g.visitor_score} - #{g.home_score}"
							- @color = "text-danger"
				

					%tr
						%td
							%h6.text-center.small{:class => @color} #{g.week}
						%td.text-center
							%h6.text-center.small{:class => @color}  #{g.date.strftime('%a, %b %-d')}
						%td.text-center
							%h6.text-center.small{:class => @color}  #{g.date.strftime('%l:%M %p')}
						- if g.home_id == t.id
							- @opp = "#{Team.find(g.visitor_id).city} #{Team.find(g.visitor_id).name}"
						- else 
							- @opp = "@ #{Team.find(g.home_id).city} #{Team.find(g.home_id).name}"
						%td.text-center
							%h6.text-center.small{:class => @color}  #{@opp}  
						%td.text-center
							%h6.small{:class => @color} #{@score}
						-# - getUserWinPercent(t.wins, t.losses, t.ties)
						-# %td.text-center 
						-# 	%h4.text-center #{@wP}
		.modal-footer.teamModalFt
			%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/shared/_teamModal.html.haml
.modal-dialog
	.modal-content
		.modal-header
			%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
			%h4.modal-title #{u.owner}
		.modal-body
			%table.table.table-striped.table-condensed.table-bordered
				%tr
					%th.col-md-5.col-sm-5.col-xs-5
						%h5.text-left  Team
					%th.col-md-1.col-sm-1.col-xs-1.text-center
						%h5.text-center  W
					%th.col-md-1.col-sm-1.col-xs-1.text-center
						%h5.text-center  L
					%th.col-md-1.col-sm-1.col-xs-1.text-center
						%h5.text-center  T
					%th.col-md-2.col-sm-2.col-xs-2.text-center
						%h5.text-center  Win %
				- i = 1
				- u.teams.each do |t|
					%tr.NFLTeamSched{:"data-teamid" => "#{t.id}"}
						%td
							%h4.text-left #{t.city} #{t.name}
						%td.text-center
							%h4.text-center #{t.wins}
						%td.text-center
							%h4.text-center #{t.losses}
						%td.text-center
							%h4.text-center #{t.ties}
						- getUserWinPercent(t.wins, t.losses, t.ties)
						%td.text-center 
							%h4.text-center #{@wP}
						- i =+ 1
		.modal-footer
			%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
			-# %button.btn.btn-primary{:type => "button"} Save changes

app/views/shared/_teamRow.html.haml
-if @auth_user
	- if @auth_user.id == @userName.id
		%tr{}
			%td.centerText
				%a{:href => "#", :class => 'playerRow', :'data-name' => t.city_abr, :'data-confirm' => "Are you sure you want to draft the #{t.city} #{t.name}?"} #{t.city} #{t.name}
	-elsif @auth_user.admin?
		%tr{}
			%td.centerText
				%a{:href => "#", :class => 'playerRow', :'data-name' => t.city_abr } #{t.city} #{t.name}
	- else 
		%tr{:class => 'playerRowB', :'data-name' => t.city_abr}
			%td.centerText #{t.city} #{t.name}
- else 
	%tr{:class => 'playerRowB', :'data-name' => t.city_abr}
		%td.centerText #{t.city} #{t.name}

-# %tr{:class => 'playerRow', :'data-name' => t.city_abr}
-# 		%td.centerText #{t.city} #{t.name}

		

app/views/shared/_teamsAvailable.html.haml
- if @auth_user
	- if @auth_user.id == @userName.id || @auth_user.admin?
		- @hover = "table-hover"
	- else
		- @hover = "table-opacity-low"
- else
	- @hover = "table-opacity-low"
-# - @hover = "table-hover"

%div{:class => 'col-md-3 col-sm-6 col-xs-12'}
	%table{:class => @hover + ' table table-striped col-md-3 col-sm-6 col-xs-12'}
		-# %tr
		-# 	%th{:class => 'nBox'} Name
		- @teams1.each do |t|
			= render :partial => 'shared/teamRow', :locals => {:t => t}
%div{:class => 'col-md-3 col-sm-6 col-xs-12'}
	%table{:class => @hover + ' table table-striped col-md-3'}
		-# %tr
		-# 	%th{:class => 'nBox'} Name
		- @teams2.each do |t|
			= render :partial => 'shared/teamRow', :locals => {:t => t}
%div{:class => 'col-md-3 col-sm-6 col-xs-12'}
	%table{:class => @hover + ' table table-striped col-md-3'}
		-# %tr
		-# 	%th{:class => 'nBox'} Name
		- @teams3.each do |t|
			= render :partial => 'shared/teamRow', :locals => {:t => t}
%div{:class => 'col-md-3 col-sm-6 col-xs-12'}
	%table{:class => @hover + ' table table-striped col-md-3'}
		-# %tr
		-# 	%th{:class => 'nBox'} Name
		- @teams4.each do |t|
			= render :partial => 'shared/teamRow', :locals => {:t => t}

app/views/shared/_teamsByPoints.html.haml
.modal-dialog
	.modal-content
		.modal-header
			%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
			%h4.modal-title Teams by Points
		.modal-body
			%table{:class => 'table table-striped table-condensed'}
				- @y = 1
				%tr
					%th{:class => 'col-md-1 centerText'} Pick
					%th{:class => 'col-md-5 centerText'} Team
					%th{:class => 'col-md-2 centerText'} Players
					%th{:class => 'col-md-3 centerText'} Proj. Points
					%th{:class => 'col-md-3 centerText'} Proj. Weekly
				- @teamsList.each do |t|
					%tr
						%td #{@y}
						%td{:class => 'centerText'} #{t.owner}
						%td{:class => 'centerText'} #{t.players.count}
						%td{:class => 'centerText'} 
							= SumPosPoints(t.players, "rank3")
						%td{:class => 'centerText'}
							=CalcWeeklyPoints(@posPoints, 16)
					- @y += 1

app/views/shared/_userTeam.html.haml
#UserTeams.col-md-10.col-md-offset-1.col-sm-12.col-xs-12
	%table{:class => 'table table-striped table-hover'}
		%tr
			%th.col-md-5.col-md-offset-1.col-sm-5.col-xs-5.text-left Team
			%th.col-md-1.col-sm-1.col-xs-1.text-center Win
			%th.col-md-1.col-sm-1.col-xs-1.text-center   Loss
			%th.col-md-1.col-sm-1.col-xs-1.text-center   Tie
			%th.col-md-2.col-sm-2.col-xs-2.text-center  Win %
		- u.teams.each do |t|
			%tr
				%td.text-left
					%h4 #{t.city} #{t.name}
				%td.text-center
					%h4 #{t.wins}
				%td.text-center
					%h4 #{t.losses}
				%td.text-center
					%h4 #{t.ties}
				- getUserWinPercent(t.wins, t.losses, t.ties)
				%td.text-center
					%h4.text-center #{@wP} 